// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqkpumqftndlxollflif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlxa3B1bXFmdG5kbHhvbGxmbGlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1MDIxNjMsImV4cCI6MjA3ODA3ODE2M30.CSL6i7aPr8pRDbJgQHOvKiB1Zc0j1iMPVBeQr-LHcZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});